# File: netlify.toml

# Impostazioni per la build del progetto
[build]
  command = "npm run build" # Comando per costruire il sito
  publish = "dist"          # Cartella da pubblicare

# Regola per le Single Page Application (SPA) come React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200